import random

def GetScore(Motifs):
   # Calculates the score of a motif matrix (sum of mismatches in columns)
    k = len(Motifs[0])
    t = len(Motifs)
    score = 0
    for j in range(k):
        counts = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
        for i in range(t):
            counts[Motifs[i][j]] += 1
        score += (t - max(counts.values()))
    return score

def GetProfileWithPseudocounts(Motifs):
    #Creates a Profile matrix using Laplace's Rule (adding 1 to all counts).
    t = len(Motifs)
    k = len(Motifs[0])
    profile = [[1.0] * k for _ in range(4)]
    nuc_to_idx = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
    
    for j in range(k):
        for i in range(t):
            nuc = Motifs[i][j]
            profile[nuc_to_idx[nuc]][j] += 1
        for r in range(4):
            profile[r][j] /= (t + 4)
    return profile

def ProfileRandomlyGeneratedKmer(Text, k, Profile):
    
    #Calculates probabilities for all k-mers in Text given the Profile, and randomly selects one based on those probabilities.
    
    nuc_to_idx = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
    probabilities = []
    
    # 1. Calculate probability for each k-mer
    for i in range(len(Text) - k + 1):
        pattern = Text[i:i+k]
        prob = 1.0
        for j in range(k):
            prob *= Profile[nuc_to_idx[pattern[j]]][j]
        probabilities.append(prob)
    
    # 2. Normalize probabilities so they sum to 1
    total_prob = sum(probabilities)
    if total_prob == 0:
        # Fallback if all probs are 0 (unlikely with pseudocounts)
        return Text[random.randint(0, len(Text) - k):][:k]
    
    normalized_probs = [p / total_prob for p in probabilities]
    
    # 3. Weighted random selection
    # random.choices returns a list, so we take the [0] element
    selected_index = random.choices(range(len(probabilities)), weights=normalized_probs, k=1)[0]
    
    return Text[selected_index : selected_index + k]

def GibbsSampler(Dna, k, t, N):
    # 1. Randomly select initial motifs
    Motifs = []
    for string in Dna:
        start = random.randint(0, len(string) - k)
        Motifs.append(string[start:start+k])
    
    BestMotifs = Motifs[:]
    BestScore = GetScore(BestMotifs)
    
    # 2. Iteratively improve motifs
    for _ in range(N):
        # i: Randomly choose one sequence to ignore/update
        i = random.randint(0, t - 1)
        
        # Create profile from all motifs EXCEPT sequence i
        reduced_motifs = Motifs[:i] + Motifs[i+1:]
        Profile = GetProfileWithPseudocounts(reduced_motifs)
        
        # Select a new motif for sequence i based on the profile probabilities
        Motifs[i] = ProfileRandomlyGeneratedKmer(Dna[i], k, Profile)
        
        # Check if this new set is better
        current_score = GetScore(Motifs)
        if current_score < BestScore:
            BestScore = current_score
            BestMotifs = Motifs[:]
            
    return BestMotifs

def RunGibbsSampler(Dna, k, t, N, starts=20):
    GlobalBestMotifs = []
    GlobalBestScore = float('inf')
    
    for _ in range(starts):
        current_motifs = GibbsSampler(Dna, k, t, N)
        current_score = GetScore(current_motifs)
        
        if current_score < GlobalBestScore:
            GlobalBestScore = current_score
            GlobalBestMotifs = current_motifs
            
    return GlobalBestMotifs
#sample from study course
if __name__ == "__main__":
    # Sample Input Parsing
    input_str = """15 20 2000
    AACCGTGGAATGAAGCCCGTTGCCGCTGGGAGGCATTGAGGGTGCTGAGGATAGTGGCTAGCAGGTAGCCACCGTGTAGCGTTGCGATCCCGAGGTATCTCTAGCGACCATAGATCCAGAGAACAGTAAGGGACGATGGTAGTGCTGAACAGTGACGATTGCACTTTTAGGGAGCGAGTTGAGTCGTATCATGCTGCTAGTGTTGGATTCGCAATCTACAAGCCAGTCACTGCCTGGGCATCGCGAGGGGCACATATGATTCCTCCCATCGGCAATCGTGACCCGCCCCTGGGGCCAATGATCGGCGCCTAGTAACCGTGGAATGAAG CCCGTTGCCGCTGGGAGGCATTGAGGGTGCTGAGGATAGTGGCTAGCAGGTAGCCACCGTGTAGCGTTGCGATCCCGAGGTATCTCTAGCGACCATAGATCCAGAGAACAGTAAGGGACGATGGTAGTGCTGAACAGTGACGATTGCACTTTTAGGGAGCGAGTTGAGTCGTATCATGCTGCTAGTGTTGGATTCGCAATCTACAAGCCAGTCACTGCCTGGGCATCGCGAGGGGCACATATGATTCCTCCCATCGGCAATCGTGACCCGCCCCTGGGGCCAATGATCGGCGCCTAGTAACCGTACACCGATTTAGAAAGGAATGAAG CCTGCGCAAACCAAAATTCCGGAACCTCAGAGAATTTGCGTTTCCTCGCCAGCTAATGGACTAACGCTTAAAGTAGTGCTCTTACTCACCTTGCTTGGTGGTCTCGCAGACCCTAGCACAGGATTTCTTGAAACACTTAAATGGTAACGATGCTCCCAGCGTACTGCACGCAAGCCACCTTCGTGGACTCGAGCTTCGACTATAGTACTGATGCTCCTAACATTAACTGTTTTTCTTTTGTTCGCCGTGAGCTGACAATAACCGGTTTAACAAAACAACACACTAATTTAGAAATATGGGTCAACTTCTAGTACGTAAGTAATGGTGC AAACGGCGCTGCGTTCCTACAAAGACGTGACCTCTCAGTCACTTAACCCGTCTATCTTAAAGAGCGTCCACGAAGATGTATTTCTATATAATGTAACATGTCAGTAGAAACACCAGGGCTTAAGCACGAGGCCTCGAGTTTATAGCTGCATAGGCATCTATTACAGTGCGTCTCAAAGCCTCGCCGATAAGCCATATCCACCATACGAATGGCGAAACGACTATTTCACAACCCACTATCGAAACCCGACCTCGGAATTAGAGCTGTACTGTACTGGATCGTTTGGAGATTAGGGAGTCCCCGCGAGAACGGGATTGCGCTCAGTTGA ACTTGGCACACGTGATGTGATGCGTATTGACGAATTTGAATTACTCATATGATACCAGCAATAACTTCAAATAAGGGCCCCTGACGTCATAACACTACTTTTCTAATTCTGACATTTTCCTTTAGTATGGGTGTATCGAACCATTGTATTTAGAAAATATCCAGTATGCCTCTTCCGACCAGGATGAGGCACAAATGGTTGCGAGATCCTGACCGCTTACCCTCGCCGGCGTATGAATGAGACTCGCTAATGTTTCACCAGATGATTTTAGAGCAGGAGTCGCCCTACTCGATAGGGACTCCCTAACCCGGGCATCATCGCTTACCAA GCCCACATGTATGAGGAAACAGAAGCCGACGTCGTAGCGACCTCTTTGACTCTCCGAAGCTGATGGCTCCCCCAGCACTTTGATATCGCCTAGACGCTAAAGACTTCAAAGGAGACTTATAATACTATTTCAGTTAGGATAGAAGCTTACTGTTACAATCATCTAACCACCGAATTATCAACCCCCTCTCGGTCCGTGGTGATTAATTGATATCTGCCCGCCTCCCTACTGATGCAGGACTGCCGCTCTGATCACCCAGGCCTCTCCCATAGCGAAGACGTGTGTTCGCCGCTGCCGACTCGCTGTGCAGTGGGATAGACGTGACCAG TACATTGGTTTAGAAATGTCACCACTCTTAGTAACGTTCTACCCCAGAAGTGGCAAAGGGTGGCAGTACTGGAACGATTGGTAAGGATCCAGTCGGTAGTCGATAGAGATACATGCACGTATGCCATGTCCTCCTCGCGGAGAGTGTTTTCGGTGGTAATGTGAATAAAAGGTGTAGTCGATTTCACCTTGGCGTGGCCCACAGTTGATGTGACGGCACCTCTCAATTACCACTTCGCCTGGCACCGTATTCGTTCGTATACGACGACGTTGCTCGTCCATTAGGCTAAGAGGGCCATATAGGTAAGCTTGTCGTAGCATAACTTATA GACGGCTCGTGTCCGGGTTTAGGAACTCCACAATCTGTTGCACGCCTTCATATTTTGTTTCATTCAAGAACCCGATTGCTCTCCGCTGGAGAATTAGCGTTTGTCCTGCGAAGCTTGCGGCGGCTTGCGTCGATGAGAATAGAACCTACGATTTGCAGTTCTCAGAGTATGCACATTCCCATCCTGTTGTCCACAGCGCTCTCTACGAACGTCTCTAACGTATCAGGACCGATATCAAAAAGTTCATCGGACAGTTGTTGCCATAGGGCTTCGCAGGGGGTGTAGAGCCCTCGGTACATGTATTATTAAAAGAACGGGTACAGAGAGA GTAGAAATTGAAATTATTTGCGTAACGGATGGCTATAGTACTGCGGTGACCGGGGCTTCCAGAAGCATGCTTTTGGCATAATCTCGCGACCCCGTCTACAGAATGGTTCCACACAGGTTGTTTGGTTTAGTGTACGACCTCTTGTTTGCGTTTAGATGTAAAGCCAATCGTCGCAGGCTCTTGGAAGACCAACATGTATTTAGCGGGTGGAAGGTTCCAGCCAGGCCCTGTTTAACCGTCAAGCGACTTGCCGCAACTGAGTCAGAAGGATACCATGTTCCAGGTAGCAACCGAGCCACAAAAGATATATACTATAGGACGGACGCGA GTCAACGGAGTAAAGCCGTGCCTGCCCTTTATGAAGCAGCGTATTCACTCGTGCATGCTAAATGCATCGCTTATTCTGAGCACCCGCATTAGCATGCTGGAAACAACAGTAGACGTAGATTGCGGCATGCTTATCGTGGCAGGGTCTGTAGCTTTAAATTCGCCTGTACAAGTCCCTGACAGAGATGCAAAAGCAAAGCTCCATAGGGCAACGCGCGTCTAAAGGGGCTACCAACTAAACATAATGCGAGGCCTTGCTCAACTCCCAACAAAGTGTGTGATATCACAGTGCCATGTGGCCAAATGACATGTAAGAAGAAAGTATAGTG ACACACCCTAGAGGTGATTTACCTCCACATCGTCATTAGTCGGAAGTTCTGTACTAGCGTCGTGCGCGTCGGCTATTGAAATTGGCAGAACCAGGAGCTGTTACTAACGCTAAACCGAATGTTAGGCCGCCTGGTTGCGGTATTGCATCTTAAGAACGACAAGCGAAGAATGTATTTAGAATGCCGAACTTATCTCACCAGCGAGGACACCCCTAGAATCTAAACAAAGGGACCATTTGTTCCCTATGACCCTGACCAGGTAGTTTGGTTGTCCAGCGCTTGACATGCACACGGTACATAGTGACGCTGAAGCCGGATCAGCAGGTCG AACCACTGAATAGGCTCTGTGTCTGTGTTACCGCCCATCTGACCTATTATCTGCCTTGTAAGTTATTTTTTATACAGTATGTTCGTGACCGGACTTGTCTATGCATATTAGACAGGTCATTACGCGGGGTTTCTTAAGGAGCCCTACGACGTGTCTCCGGTGTCAAAATACATGGATTGTCATGGCCGACACGTTGTGTTACATGTATTTACCGAGATTTTGGACCCTACGACTAGCCAGGTGCAGTTATGTATTTAAGTGTCGCTAGACAAAGGCTGTATGGGCCTATATTTGCACGGTCGTAAACTGCGCGGCTAAGTTCATACCA ATACTAAACTACGTAAACACGTCTAACTCTGAGGAAAGCAATACCGTTGGTTAGAGGCGGCGAGAGCAGCTTTCTGCTACCGCACAGGACCATAAGCTGCCGAGAAGTCCAAGTCCGGTGAGTAAACATCAGTTCCAACTAAAGATTCATGTTTTGTACATTGCTTTAGAAATTTGATGATAGGACAAATACTATGGGTCAGATCCAGGTATCACCGTGCTGCCTGACATTTGCCGCGGTGATGACTATAACAACAGCATCTACTGTGTTACGACTGAAACATGCTTTCGCTATAGACGAAGAGTGGTTGGCAAATAGTCTAAATAAG GCGAGGCTGTAGCTGATCGTCTCTGTGTGTCGTCCTGCTTATAAGCCAGAAGGACATATAGCAAGGGGGAGGAGCAGCGTTGTCATCTCTGAAAGAGTATTTAGAAACAAAGCAATGGATTTCATAACGCGAAGCATACAGAGGAAGTAGCGATCATAACCGTCGAACTGAGTAGCTCCTGCCGACTCGTCGCTTTGGAAGCATGAAGCTTGACCTCTTGAACCTCTCCACTAACCCTAATCTTTAGTTTTGATGTTATCTTGCAACCACTAATGGCCGCAGGGCGCGTACACTAGTGTCCTGGGACTAGCTAGGATGTGCCCAGGTT CATAATACCTTTTGGGGGGGTAAGTCAGTCATGTAGGTAGTTCACCAAATCTGCGGCATGTATTTAGAGCACTCTACCGAGGGGCCTGTGGTATAATTTAAAGGTTGGTGCGCGACAAATAGCATTTCAGGTGTTGCAAGAGTGAGTTTTAGGCTTAATGCCAGCCCTCTTTGCCCTCGTATGGGTTGATCCAAAAGAAACCTAGCACGGTGTGCCGTCCCAAACCGCTTCCTTCGGTAGCAGACCCAGAATAACGGAGGCGAGGTGAGACGCACTTCGACTATGCCTTTGAAAACGGTCAGGTCTGAGTGCTAGGGCCCATACTCAC GTATCATTCCAGGTCGGATCGGGAGTCCTAAATCAAAACTGTAGACTAATTTAATGCGCGACGTTAGTCCAAAGCAGGACATGAGGTTAGAAATATCTGGCGAAAAGTTCTTATACGACCCGAGATCTGAAATGGCACGACAATCATTCTTCGGTACGACGTGCGGACAGTAACACTTATTCATTTAGCATTCTGTAGAGCGTGCTCGGTAGCATTGCCCCTTACCGTAGCTATAGTCCGTGGGTGACGCTCCCAATCCGGTTGAAGAGACGATAGGTAGACATTTTACAGCGTATATTCTAGTTCTTGCTGCTACGCAGTTTATTAT CTACGTTTGTACGGTATCTCGTATAAACGACGAAGACACTATTATTTAGAAAGAGGGGAGTGTAATCAATTCCAGCATCCCCATACTTGAACGGCTCTAGTTGTAATAGGTTGCAGAAAGTATCGTACTGCCTCTTGTTTGGACTCTTGAATGACTCGAAGACCAAAGTGGTCGCTAGGCCCGATTCCGGCAAGAGACCTGTAGTCGGTCGAGCTGGCATTCAAGTCCGTGCGGCGTTCCGAAATTACGAGTCATCCCTACCACCTCGTATCGGGCATTTTTTATGAGCCATAGGACTACAACGGTGCGTAATTATCGAGGCGCATCA ATCCCCTTTATTACGGGATCGGAATGTGCCAGCATCCAAAGGGCGCTCAAGATCCTTATACGCATTTGCGTAGCCCCCCAAACTCCCTTACCTGCATCTGCAGCTTGGAAGTTGTGAGAACACCTCACGGAATCGTAGGGAGAATATTAGTGGCGACAACCAGTAGCAGCCTCCGGGTACCTCCATCCGCAATTCAGAAAAATGGGCATTGCTCATTAGTCACATGTATTTGTCAATTTGGACCACGTCGGTCCAATGAGCGATCGTAAGAAACTCTCTGGGTGATGCGGCATGAGACCTTGCACTGGTACCAAGCGCACCTCGCTCG CCACTAAAGTGTTGCGTTGCCAAGCCTCTTGGTAGCTGTATTACAACCAGCGAAGAATGTGACCGGTTGAGTCGGCAATGGGTTCTGATTGCGGAATGCGTGGCCCGAGTTGGTCCGGCATGAGGCGGGAACTGCTCAGACTTGTAAGCATGTGCGCACTCCGTGTGGCACACGCCGAGGTCAGGGTAACGCGCGCTATATAACATGTCGGTAGAAATGCGGCGCCTGTATAGCTCTCATGCGCGCCAGTCCTGAGCAAATGTTATATAACGACTGATAAGTATCTGTTCTTGTCATTTACTCGGGGTTTCGATTTTCCTCTGGTTGT ATGCTTTCGGTGTCCAGGCGGGATCCCCCTACCATTACTTAGGTGAGCGACCTTAACTTCGTCGCACGCTGGCAGAGTGTATGCCCGAATACGGATACGATGATGCTCGAATAATTCTATAATTCATAACGATATAACATGCGATTAGAAATTTTGTCTATGTAAAAATGTCCACCGGGAAGCAAAACTCGCAATTAGCTGTATAGTTCTCGTCGAAAACCCAGGACATAGCATCGGCTCCGCTCTCGCGATATGCGCTTCAATCTGAAAGTTAAGGGCGCCCTCCGGAGAGAAGTGGCAAATTGTCTTGCGATGCATGGTGGAGAGT"""
    
    # Split input to separate integers and DNA strings
    parts = input_str.split()
    k_in = int(parts[0])
    t_in = int(parts[1])
    N_in = int(parts[2])
    dna_in = parts[3:]
    
    # Run the sampler with 20 random starts
    result = RunGibbsSampler(dna_in, k_in, t_in, N_in, starts=20)
    print(" ".join(result))
